### ISSUE TITLE
Issues when command #craft browse fired

### ISSUE THREAD

**Issue by DrHeretic** [promcteam/prorpgcrafting#16]
Using current versions of Prorpgcrafting and dependencies needed Procut/Risecore

![image](https://user-images.githubusercontent.com/88398845/201573677-2f7d28fc-e13b-4a65-8f04-6d9fc83a7824.png)
Browse .yml
![image](https://user-images.githubusercontent.com/88398845/201573717-abb86b65-e1de-43fc-a5ef-34de363a9452.png)

**Comment by goflishMC** [comment]
> Using current versions of Prorpgcrafting and dependencies needed Procut/Risecore
> 
> ![image](https://user-images.githubusercontent.com/88398845/201573677-2f7d28fc-e13b-4a65-8f04-6d9fc83a7824.png) Browse .yml ![image](https://user-images.githubusercontent.com/88398845/201573717-abb86b65-e1de-43fc-a5ef-34de363a9452.png)

this was fixed, the build will be posted soon to discord
