### ISSUE TITLE
Add option to use ProRPGItems as the item database

### ISSUE THREAD

**Issue by goflishMC** [promcteam/prorpgcrafting#21]
Add a new option in the config to set ProRPGItems or ProMCUtilities as the item database

Example
<pre>
# Select which plugin will handle the item database
# This determines the names you use when setting up
# Your recipes.
# If using prorpgitems prefix your recipes with "module_name"
item_storage: prorpgitems/promcutilities
</pre>

Set it to prorpgitems by default on new install.

**Comment by Sentropic** [comment]
Solved by https://github.com/promcteam/prorpgcrafting/commit/468d6669a624c437d6536c115d7eeed261ee3475:
You can now use any ItemTypes (like `PROMCU_sword` or `PRORPGITEMS_axe`) without having to specify any database.
