### ISSUE TITLE
Remove hard dependency for ProMCUtilities

### ISSUE THREAD

**Issue by goflishMC** [promcteam/prorpgcrafting#22]
Only require ProMCUtilities if it's selected as the item storage.

**Comment by Sentropic** [comment]
Solved by https://github.com/promcteam/prorpgcrafting/commit/468d6669a624c437d6536c115d7eeed261ee3475:
You can now use any ItemTypes (like `PROMCU_sword` or `PRORPGITEMS_axe`) without having to specify any database.
